# Generated by Django 4.1.2 on 2022-11-06 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=64)),
                ('stake', models.FloatField()),
                ('odds', models.FloatField()),
                ('total_lost', models.FloatField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 11, 6, 13, 7, 12, 709361))),
            ],
        ),
    ]
