# Generated by Django 4.1.2 on 2022-10-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_lose', models.IntegerField()),
                ('stake', models.IntegerField()),
                ('odds', models.IntegerField()),
                ('target', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
    ]
