# Generated by Django 4.1.2 on 2022-11-06 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 13, 7, 40, 89728)),
        ),
    ]
