# Generated by Django 4.1.2 on 2022-10-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='odds',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bet',
            name='profit',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bet',
            name='stake',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bet',
            name='target',
            field=models.CharField(max_length=64),
        ),
    ]
