# Generated by Django 4.1.2 on 2022-11-08 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bet_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='progression',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 8, 25, 3, 310571)),
        ),
    ]
