# Generated by Django 4.1.2 on 2022-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bet_odds_alter_bet_profit_alter_bet_stake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='progression',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
