# Generated by Django 4.1.2 on 2022-10-24 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bet_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 17, 7, 29, 899918, tzinfo=datetime.timezone.utc)),
        ),
    ]
