# Generated by Django 4.1.2 on 2022-10-24 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bet_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 20, 9, 18, 516751)),
        ),
    ]
