# Generated by Django 4.1.2 on 2022-11-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bet_balance_alter_bet_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='balance',
            field=models.CharField(max_length=64),
        ),
    ]
