# Generated by Django 4.1.2 on 2022-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_bet_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
