# Generated by Django 4.1.2 on 2022-10-26 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_win_lose_bet_result_alter_bet_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='balance',
            field=models.CharField(default=200, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 11, 0, 36, 27787)),
        ),
    ]
