# Generated by Django 4.1.2 on 2022-11-02 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_bet_balance_alter_bet_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='balance',
            new_name='total_lost',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='progression',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='target',
        ),
        migrations.AlterField(
            model_name='bet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 7, 39, 33, 316826)),
        ),
    ]
